name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: simpleactions/create-tag@v1.0.0
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
